import Head from 'next/head'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MD. TAHIDUR RAHMAN</title>
        <meta name="description" content="Generated by tahidur tuhin portfolio" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}
